In [17]:
import pandas as pd

df_flight=pd.read_csv('flight_environment_dataset.csv')
df_aqi=pd.read_csv('clean_aqi.csv')

## flight_environment_dataset

In [6]:
print('Shape:', df_flight.shape)
df_flight.head()

Shape: (27626, 26)

,scheduled_arrival_datetime,scheduled_hour,status,able_to_land,flight_number,callsign,airline,origin_city,origin_iata,arrival_hour,...,pm2_5,temperature_2m,relative_humidity_2m,precipitation,snowfall,cloud_cover,wind_speed_10m,wind_gusts_10m,weather_code,smog_risk
0,2022-03-30 07:55:00,2022-03-30 07:00:00,Landed,1,EW492,EWG492,Eurowings,Cologne,CGN,7,...,19.8,5.2,87,0.0,0.0,100,4.6,20.9,3,0
1,2022-03-30 08:15:00,2022-03-30 08:00:00,Landed,1,TK1021,THY1MY,Turkish Airlines,Istanbul,IST,8,...,20.6,7.5,81,0.0,0.0,100,5.0,20.5,3,0
2,2022-03-30 10:20:00,2022-03-30 10:00:00,Landed,1,PC291,PGT51F,Pegasus,Istanbul,SAW,10,...,20.4,12.3,60,0.0,0.0,100,2.7,16.6,3,0
3,2022-03-30 11:40:00,2022-03-30 11:00:00,Landed,1,LH1544,DLH5HH,Lufthansa,Frankfurt,FRA,11,...,18.5,13.5,56,0.0,0.0,100,4.7,20.5,3,0
4,2022-03-30 13:10:00,2022-03-30 13:00:00,Landed,1,W64760,WZZ10CV,Wizz Air,Oslo,TRF,13,...,19.0,14.3,49,0.0,0.0,100,12.4,36.7,3,0

In [7]:
df_flight.dtypes

scheduled_arrival_datetime     object
scheduled_hour                 object
status                         object
able_to_land                    int64
flight_number                  object
callsign                       object
airline                        object
origin_city                    object
origin_iata                    object
arrival_hour                    int64
day_of_week                     int64
month                           int64
is_winter_month                 int64
aqi_datetime                   object
european_aqi                    int64
pm10                          float64
pm2_5                         float64
temperature_2m                float64
relative_humidity_2m            int64
precipitation                 float64
snowfall                      float64
cloud_cover                     int64
wind_speed_10m                float64
wind_gusts_10m                float64
weather_code                    int64
smog_risk                       int64
dtype: object

In [8]:
df_flight.isnull().sum()

scheduled_arrival_datetime      0
scheduled_hour                  0
status                          0
able_to_land                    0
flight_number                   0
callsign                      159
airline                         0
origin_city                     0
origin_iata                     0
arrival_hour                    0
day_of_week                     0
month                           0
is_winter_month                 0
aqi_datetime                    0
european_aqi                    0
pm10                            0
pm2_5                           0
temperature_2m                  0
relative_humidity_2m            0
precipitation                   0
snowfall                        0
cloud_cover                     0
wind_speed_10m                  0
wind_gusts_10m                  0
weather_code                    0
smog_risk                       0
dtype: int64

In [9]:
df_flight.describe()

,able_to_land,arrival_hour,day_of_week,month,is_winter_month,european_aqi,pm10,pm2_5,temperature_2m,relative_humidity_2m,precipitation,snowfall,cloud_cover,wind_speed_10m,wind_gusts_10m,weather_code,smog_risk
count,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000,27626.000000
mean,0.988417,14.650221,3.008289,6.726417,0.245095,39.549012,18.940614,14.816698,16.240922,65.797763,0.128368,0.011445,53.898357,5.862372,20.397108,12.193694,0.054405
std,0.107002,4.498056,2.019696,3.088652,0.430151,16.315742,15.408061,13.825802,8.546385,18.662436,0.583564,0.115364,41.418199,3.436162,9.481399,21.861188,0.226820
min,0.000000,1.000000,0.000000,1.000000,0.000000,13.000000,2.000000,1.600000,-13.200000,11.000000,0.000000,0.000000,0.000000,0.000000,2.500000,0.000000,0.000000
25%,1.000000,11.000000,1.000000,4.000000,0.000000,28.000000,9.800000,7.500000,10.000000,51.000000,0.000000,0.000000,9.000000,3.300000,13.700000,0.000000,0.000000
50%,1.000000,14.000000,3.000000,7.000000,0.000000,34.000000,14.900000,11.100000,16.700000,67.000000,0.000000,0.000000,55.000000,5.400000,18.700000,2.000000,0.000000
75%,1.000000,18.000000,5.000000,9.000000,0.000000,45.000000,22.600000,16.800000,22.600000,81.000000,0.000000,0.000000,100.000000,7.700000,25.200000,3.000000,0.000000
max,1.000000,23.000000,6.000000,12.000000,1.000000,117.000000,235.100000,227.600000,37.300000,100.000000,22.500000,3.150000,100.000000,33.300000,94.700000,75.000000,1.000000

In [10]:
print('status:\n', df_flight['status'].value_counts())
print('\nable_to_land:\n', df_flight['able_to_land'].value_counts())
print('\nsmog_risk:\n', df_flight['smog_risk'].value_counts())
print('\nTop airlines:\n', df_flight['airline'].value_counts().head(10))

status:
 status
Landed       27306
Cancelled      237
Diverted        83
Name: count, dtype: int64

able_to_land:
 able_to_land
1    27306
0      320
Name: count, dtype: int64

smog_risk:
 smog_risk
0    26123
1     1503
Name: count, dtype: int64

Top airlines:
 airline
Turkish Airlines     4246
Austrian Airlines    2766
Pegasus              2578
Croatia Airlines     2577
Lufthansa            1658
Ryanair              1612
Air Serbia           1424
Wizz Air             1325
flydubai             1244
flynas               1055
Name: count, dtype: int64

## clean_aqi

In [11]:
print('Shape:', df_aqi.shape)
df_aqi.head()

Shape: (35064, 16)

,datetime,european_aqi,pm10,pm2_5,temperature_2m,relative_humidity_2m,precipitation,snowfall,cloud_cover,wind_speed_10m,wind_gusts_10m,weather_code,hour,day_of_week,month,smog_risk
0,2022-03-30 00:00:00,64,24.6,23.1,5.4,84,0.0,0.0,16,4.0,15.8,0,0,2,3,0
1,2022-03-30 01:00:00,63,26.0,17.6,4.4,87,0.0,0.0,61,4.2,18.0,2,1,2,3,0
2,2022-03-30 02:00:00,62,26.0,16.5,3.9,86,0.0,0.0,70,8.0,18.4,2,2,2,3,0
3,2022-03-30 03:00:00,62,25.2,16.1,5.1,84,0.0,0.0,66,4.8,24.5,2,3,2,3,0
4,2022-03-30 04:00:00,61,31.2,17.2,4.7,85,0.0,0.0,100,4.8,19.4,3,4,2,3,0

In [12]:
df_aqi.dtypes

datetime                 object
european_aqi              int64
pm10                    float64
pm2_5                   float64
temperature_2m          float64
relative_humidity_2m      int64
precipitation           float64
snowfall                float64
cloud_cover               int64
wind_speed_10m          float64
wind_gusts_10m          float64
weather_code              int64
hour                      int64
day_of_week               int64
month                     int64
smog_risk                 int64
dtype: object

In [13]:
df_aqi.isnull().sum()

datetime                0
european_aqi            0
pm10                    0
pm2_5                   0
temperature_2m          0
relative_humidity_2m    0
precipitation           0
snowfall                0
cloud_cover             0
wind_speed_10m          0
wind_gusts_10m          0
weather_code            0
hour                    0
day_of_week             0
month                   0
smog_risk               0
dtype: int64

In [14]:
df_aqi.describe()

,european_aqi,pm10,pm2_5,temperature_2m,relative_humidity_2m,precipitation,snowfall,cloud_cover,wind_speed_10m,wind_gusts_10m,weather_code,hour,day_of_week,month,smog_risk
count,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000,35064.000000
mean,40.498488,22.280963,18.401283,12.267077,74.969770,0.120254,0.014276,56.732204,5.461111,18.664511,11.847878,11.500000,3.003422,6.522930,0.100074
std,17.853278,17.859747,16.686919,8.562893,17.738089,0.534914,0.123247,42.250326,3.119055,9.218308,21.865846,6.922285,1.999170,3.448752,0.300103
min,13.000000,1.900000,1.300000,-14.100000,11.000000,0.000000,0.000000,0.000000,0.000000,2.200000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,27.000000,11.400000,8.900000,5.600000,63.000000,0.000000,0.000000,8.000000,3.300000,12.200000,0.000000,5.750000,1.000000,4.000000,0.000000
50%,34.000000,17.300000,13.300000,12.000000,80.000000,0.000000,0.000000,68.000000,5.000000,16.600000,2.000000,11.500000,3.000000,7.000000,0.000000
75%,54.000000,26.500000,21.000000,18.400000,89.000000,0.000000,0.000000,100.000000,7.100000,22.700000,3.000000,17.250000,5.000000,10.000000,0.000000
max,117.000000,235.100000,227.600000,37.300000,100.000000,22.500000,4.690000,100.000000,33.600000,94.700000,75.000000,23.000000,6.000000,12.000000,1.000000

In [16]:
print('smog_risk:\n', df_aqi['smog_risk'].value_counts())
print('\neuropean_aqi—min:', df_aqi['european_aqi'].min(), '| max:', df_aqi['european_aqi'].max(), '| mean:', round(df_aqi['european_aqi'].mean(), 2))
print('pm2_5—min:', df_aqi['pm2_5'].min(), '| max:', df_aqi['pm2_5'].max(), '| mean:', round(df_aqi['pm2_5'].mean(), 2))

smog_risk:
 smog_risk
0    31555
1     3509
Name: count, dtype: int64

european_aqi—min: 13 | max: 117 | mean: 40.5
pm2_5—min: 1.3 | max: 227.6 | mean: 18.4